### ISSUE TITLE
build args default should be 'quiet'

### ISSUE THREAD

**Issue by Seasawher** [leanprover/lean-action#58]
output messages are usually unnecessary.

**Comment by austinletson** [comment]
In my view, we should use the default configuration provided by `lake build` unless there is a highly compelling reason for an alternative configuration for `lean-action` specific `lake build`. If you want a different default configuration for Lake, create this as an RFC on [leanprover/lean4](https://github.com/leanprover,/lean4), where Lake is under development, and make the case there.

**Comment by Seasawher** [comment]
ok I understand
